/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Event {
  title: string;
  description?: string;
  date: string;
  location: {
    address: string;
    city: string;
    postalCode: string;
    [k: string]: unknown;
  };
  attendees: {
    name: string;
    email: string;
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
