/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Product {
  id: string;
  name: string;
  price: number;
  tags: string[];
  inStock: boolean;
  dimensions: {
    length: number;
    width: number;
    height: number;
    [k: string]: unknown;
  };
  warehouseLocation?: {
    latitude: number;
    longitude: number;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
